Feature/fourth widget
solid-software/help_ukraine_widget pull request #28
Opened 2022-09-01 12:09 UTC by F1fi

2022-09-02 10:45 UTC, solid-yuriiprykhodko commented
<img width="304" alt="image" src="https://user-images.githubusercontent.com/40931732/188123260-464bd5c8-189d-4514-af16-a4e24fb24452.png">

Take a closer look at the font weights, make sure you're using the right font family.

2022-09-02 13:21 UTC, solid-yuriiprykhodko commented
For the main view all sizes match, except for the flag emoji -- which affects widget width.

<img width="322" alt="image" src="https://user-images.githubusercontent.com/40931732/188154802-2be63fec-a10b-4276-b535-ff777986311b.png">

My take is that it's completely fine. @illia-romanenko what do you think?

2022-09-02 13:33 UTC, F1fi commented
![image](https://user-images.githubusercontent.com/93270530/188157127-a401bfb6-19fc-4d4c-b990-577ea190c3d3.png)
fist - our widget,
second - widget from site

2022-09-02 14:27 UTC, solid-yuriiprykhodko commented
Looks like there are some problems with displaying the flag emoji.
Let's try to replace it with and SVG or an image.

2022-09-20 17:57 UTC, solid-yuriiprykhodko requested changes
Let's resolve the conflicts before moving forward.

Also please attach screenshots of the widget using the pixel-perfect tool. Suggest using the inverted image function -- makes it much easier to spot differences.

2022-09-20 19:26 UTC, solid-oleksandrhordiienko commented
<img width="569" alt="image" src="https://user-images.githubusercontent.com/113910662/191345041-0182cfda-651e-4128-8e29-8785adc188f6.png">
right - our widget,
left - widget from site
<img width="303" alt="image" src="https://user-images.githubusercontent.com/113910662/191345568-40860a68-de65-4d15-be18-d6405ce3303f.png">
one on top of other

2022-09-20 20:30 UTC, solid-oleksandrhordiienko commented
mainView
<img width="318" alt="image" src="https://user-images.githubusercontent.com/113910662/191358216-6c032526-2743-47e2-a14a-9830f04a6068.png">
one on top of other
<img width="306" alt="image" src="https://user-images.githubusercontent.com/113910662/191358336-038f2673-8e29-4769-a660-bebd0e02c97b.png">

2022-09-20 20:31 UTC, solid-oleksandrhordiienko commented
optionView (one on top of other)
<img width="270" alt="image" src="https://user-images.githubusercontent.com/113910662/191358586-d6b64939-6b28-4e7b-9288-1cb427c4752e.png">
<img width="277" alt="image" src="https://user-images.githubusercontent.com/113910662/191358633-7299b09d-04e9-4913-8dec-d0e5e82b8b5b.png">

2022-09-20 20:44 UTC, solid-oleksandrhordiienko commented
optionsView (one on top of other)
<img width="272" alt="image" src="https://user-images.githubusercontent.com/113910662/191360638-114cef79-51d1-4568-836e-37652621c88b.png">
<img width="274" alt="image" src="https://user-images.githubusercontent.com/113910662/191360718-ab4af4e8-2c07-4eb4-9a67-08d8c41fabbc.png">

2022-09-21 13:19 UTC, solid-yuriiprykhodko commented
> <img alt="image" width="306" src="https://user-images.githubusercontent.com/113910662/191358336-038f2673-8e29-4769-a660-bebd0e02c97b.png">

Make sure the "U" letter placement matches perfectly and then adjust the letterSpacing.

2022-09-21 17:21 UTC, solid-oleksandrhordiienko commented
<img width="252" alt="image" src="https://user-images.githubusercontent.com/113910662/191570208-7cfd745d-c836-446c-b63c-c65f035f689c.png">

2022-09-21 17:41 UTC, solid-yuriiprykhodko commented on example/lib/storybook/stories/help_widget_story.dart
>              );
We shouldn't be removing the second widget from the stroybook.

2022-09-21 17:42 UTC, solid-yuriiprykhodko commented on lib/src/components/card_rounded/card_rounded.dart
> +  static const _scale = 1.15;
-> `_closeButtonScale`?

2022-09-21 17:43 UTC, solid-yuriiprykhodko requested changes
There are a few changes in the base widgets -- please verify that variations 1 and 2 are unaffected.

2022-09-21 19:56 UTC, solid-oleksandrhordiienko commented
second widget
<img width="277" alt="image" src="https://user-images.githubusercontent.com/113910662/191598405-e73552b3-88c9-479d-bb80-f9f6ce0ccc9f.png">
<img width="268" alt="image" src="https://user-images.githubusercontent.com/113910662/191598549-97ce3c27-e1ac-4562-985c-83bcd05e9171.png">

2022-09-21 19:58 UTC, solid-oleksandrhordiienko commented
fourth widget
<img width="256" alt="image" src="https://user-images.githubusercontent.com/113910662/191598719-8de3cf1c-b25b-408d-9b18-5db7310656c0.png">
<img width="267" alt="image" src="https://user-images.githubusercontent.com/113910662/191598835-c82700cc-e0a8-4543-b0d4-28ab7a8c303e.png">

2022-09-21 20:04 UTC, solid-oleksandrhordiienko commented
first widget
<img width="347" alt="image" src="https://user-images.githubusercontent.com/113910662/191599853-354a857d-28d2-44b0-8e9a-b5e6f8e7cab1.png">
<img width="343" alt="image" src="https://user-images.githubusercontent.com/113910662/191599959-1d5ee71c-fa86-44ce-bfa4-03100317ea5c.png">

2022-09-23 13:22 UTC, solid-oleksandrhordiienko commented
Fourth widget
<img width="268" alt="image" src="https://user-images.githubusercontent.com/113910662/191968471-b167a798-5c53-4e8e-a421-779d306f02d1.png">
<img width="259" alt="image" src="https://user-images.githubusercontent.com/113910662/191968555-e68056a6-d7e4-4a90-affe-30293e102bdb.png">
Second widget:
<img width="279" alt="image" src="https://user-images.githubusercontent.com/113910662/191969012-3061d0e2-0e20-412c-96a9-d04294d02ff4.png">
<img width="271" alt="image" src="https://user-images.githubusercontent.com/113910662/191969093-a884323c-ed91-4e4a-a0ab-aa416f336999.png">
First Widget:
<img width="357" alt="image" src="https://user-images.githubusercontent.com/113910662/191969553-c962ada5-c76b-4115-909d-71a85a6eb69e.png">
<img width="346" alt="image" src="https://user-images.githubusercontent.com/113910662/191969655-340e4272-24f1-41a4-98ca-b60a061b7048.png">

2022-09-23 13:27 UTC, solid-yuriiprykhodko requested changes
Looks good visually -- just some cleanup suggestions.

2022-09-23 13:27 UTC, solid-yuriiprykhodko commented on lib/src/components/card_rounded/card_rounded.dart
> +            size: Size.square(_iconSize),
Same as in widget 3 -- let's adjust the size instead of scaling the x-mark.

2022-09-23 13:27 UTC, solid-yuriiprykhodko commented on lib/src/theme/help_colors.dart
> +  static const black = Color(0xFF000000);
```suggestion
  static const black = Colors.black;
```

2022-09-23 13:27 UTC, solid-yuriiprykhodko commented on pubspec.lock
> +  flutter: ">=2.11.0-0.1.pre"
Make sure you're using Flutter `stable` channel and are up to date.

2022-09-23 13:27 UTC, solid-yuriiprykhodko commented on lib/src/components/buttons/details_button.dart
> +              ).copyWith(
Why was the font family removed here?

2022-09-23 14:31 UTC, solid-yuriiprykhodko requested changes

2022-09-23 14:31 UTC, solid-yuriiprykhodko commented on lib/src/components/buttons/details_button.dart
> -                fontFamily: FontConfig.family,
The font family is still removed.

2022-09-23 15:12 UTC, solid-yuriiprykhodko approved these changes
LGTM!

2022-09-23 15:14 UTC, merged