fix #8, Feature/overlay
solid-software/help_ukraine_widget pull request #29
Opened 2022-09-01 13:15 UTC by solid-danylosafonov

2022-09-01 15:08 UTC, solid-danylosafonov commented
Small overflow in example
![image](https://user-images.githubusercontent.com/112557452/187948090-fd320cd2-b89a-45d5-b38f-815538bc71de.png)
Also probably need to add overlaywidget HelpWidget (duplicate alignment)
And I want to add knobs for alignment to example

2022-09-01 15:46 UTC, solid-danylosafonov commented
unsure about last commit: something like that will be needed for all variations, so we either write it twice (four times), or some kind of interface is needed to not rewrite that helper widget, instead we would do something like:
`
class OverlayHelpWidget<T implements IHelpWidget> extends StatelessWidget {
  final Alignment alignment;
  final Widget background;

  const OverlayHelpWidget(
      {required this.alignment, required this.background});

  @override
  Widget build(BuildContext context) {
    return OverlayWidget(
      alignment: alignment,
      overlayWidget: T(
        alignment: alignment,
      ),
      child: background,
    );
  }
}
`

and then
`
OverlayHelpWidget<HorizontalHelpWidget>(alignment)
`

also other variations [will] have multiple duplicate field

2022-09-01 15:56 UTC, solid-danylosafonov commented
> and then `OverlayHelpWidget(HorizontalHelpWidget, alignment)`
> 
> also other variations [will] have multiple duplicate field

nvm that's probably too meta and won't be possible in dart (or it won't be pretty)

2022-09-01 16:44 UTC, solid-yuriiprykhodko commented
@solid-danylosafonov Made a few changes that seem to fix the double `alignment` arg issue.

2022-09-02 07:00 UTC, solid-danylosafonov commented
![image](https://user-images.githubusercontent.com/112557452/188077597-78e7a3ec-d21b-44fb-bb38-9b9f18a577bd.png)

![image](https://user-images.githubusercontent.com/112557452/188077654-b105efcc-bafb-4e2a-b3c3-5e01df0d636b.png)

![image](https://user-images.githubusercontent.com/112557452/188077752-21d553ee-cd44-4380-ab27-8126b931236a.png)

2022-09-02 09:53 UTC, solid-yuriiprykhodko commented on example/lib/storybook/stories/help_widget_story.dart
> +                      for (var i = 0; i < _listLength; i++)
List.generate?

2022-09-02 09:54 UTC, solid-yuriiprykhodko requested changes
A small refactoring nitpick.

2022-09-02 10:03 UTC, solid-danylosafonov commented on example/lib/storybook/stories/help_widget_story.dart
> +                      for (var i = 0; i < _listLength; i++)
my bad

2022-09-02 10:04 UTC, solid-yuriiprykhodko approved these changes
LGTM!

2022-09-02 10:07 UTC, merged